### ISSUE TITLE
On Export page, Patient compartment text uses SHALL in one place and SHOULD in another

### ISSUE THREAD

**Issue by gotdan** [HL7/bulk-data#15]
Think both shall be SHOULD? 

For non-system-level requests, the [Patient Compartment](https://www.hl7.org/fhir/compartmentdefinition-patient.html) SHOULD be used as a point of reference for recommended resources to be returned.

**Comment by jmandel** [comment]
I think this has been updated -- @gotdan you can close if you're happy with the current state.

**Comment by gotdan** [comment]
Yup, I updated it to SHOULD, but wanted to make sure everyone was happy that this was a SHOULD and not a SHALL.
