### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by jmandel** [HL7/bulk-data#20]
I'll keep adding broken or problematic links to this issue as I read through. FYI @gotdan

- [ ] In http://build.fhir.org/ig/HL7/bulk-data/export/index.html#endpoint---all-patients "​View table of parameters for Patient Export" 
- [ ] In http://build.fhir.org/ig/HL7/bulk-data/export/index.html#endpoint---group-of-patients "​View table of parameters for Group Export"
- [ ] In http://build.fhir.org/ig/HL7/bulk-data/export/index.html#endpoint---system-level-export "​View table of parameters for Export"

**Comment by gotdan** [comment]
Think these are fixed now, so maybe close and reopen if we find others? Also, can you increase my permission level on this repo - I can't do things like close issues :).

**Comment by jmandel** [comment]
Great! Closing.

You should have an invite at https://github.com/HL7/bulk-data/invitations
