### ISSUE TITLE
On authorization page, should the public health use case be merged with the other examples?

### ISSUE THREAD

**Issue by gotdan** [HL7/bulk-data#29]

**Comment by ricky1uphealth** [comment]
I think this should remain as is, we got asked to specify public health use cases by a few orgs, including ONC, FHIR BCH (ken), and we have the public health HL7 group as an interested party

**Comment by gotdan** [comment]
Sure - I definitely agree that we should mention it, but it seems odd that it's the only use case among dozens that we call out. Shouldn't it be included as a bullet within the preceding examples section?

**Comment by ricky1uphealth** [comment]
Gotcha yes i will move it to this section http://build.fhir.org/ig/HL7/bulk-data/index.html#use-cases
