### ISSUE TITLE
Last paragraph in Backend Services section 6.0 is repetitive

### ISSUE THREAD

**Issue by gotdan** [HL7/bulk-data#41]
Suggest we delete the last sentence of this paragraph:

To begin the exchange, the client SHALL use the Transport Layer Security (TLS) Protocol Version 1.2 (RFC5246) or a more recent version of TLS to authenticate the identity of the FHIR authorization server and to establish an encrypted, integrity-protected link for securing all exchanges between the client and the authorization server’s token endpoint. All exchanges described herein between the client and the FHIR server SHALL be secured using TLS V1.2 or a more recent version of TLS .

**Comment by jmandel** [comment]
I'd rather not take this to FHIR-I for a vote unless there are other required changes. Let's see what else we identify this week and decide in that context.

**Comment by gotdan** [comment]
Oops, I was assuming this was added in response to the TLS 1.2 comment - not important to fix.
