### ISSUE TITLE
Update official URL to include "uv" path component

### ISSUE THREAD

**Issue by jmandel** [HL7/bulk-data#55]
Based on Grahame's feedback during FHIR Infrastructure call, I think this should be `http://hl7.org/fhir/uv/bulkdata`

**Comment by ricky1uphealth** [comment]
https://github.com/HL7/bulk-data/pull/56

**Comment by lynnlaakso** [comment]
also in npm path in ig.json?

**Comment by jmandel** [comment]
Yes, see
https://github.com/HL7/bulk-data/blob/a861f33e8d7f52a592d86db13c2d7a54b018745e/ig.json
and
let us know if you notice any issues.

**Comment by jmandel** [comment]
Fixed by #56 #57 #58 #59.
