### ISSUE TITLE
Bulk export should be invocable via HTTP POST

### ISSUE THREAD

**Issue by lmsurpre** [HL7/bulk-data#70]
http://hl7.org/fhir/uv/bulkdata/STU1/export/index.html#request-flow shows that the $export operation is invocable via HTTP GET, but I don't think it says anything about POST.

Meanwhile, the base FHIR specification indicates that operations can be invoked via HTTP POST:  https://www.hl7.org/fhir/operations.html#executing

Additionally, its says that 
> Operations may be invoked using a GET, with parameters as HTTP URL parameters, if:
> * there are only simple input parameters - i.e. no complex datatypes like 'Identifier' or 'Reference', and
> * and the operation does not affect the state of the server

Based on that, I think its OK to continue supporting `$export` via GET, but I'd like to see the bulkdata specification indicate that POST must be supported as well (and maybe even should be preferred given that GETs should be idempotent/repeatable).

There was some discussion on the bulk data argonaut call on this front and, although no one was a big fan of the FHIR Parameters object, this is the wrapper that FHIR specifies for passing parameters while invoking extended operations like `$export` via POST.

**Comment by gotdan** [comment]
Fixed in #71
